# SiFive je bil nekoc prosto dostopen.
# Sedaj hocejo, da se registriras... da prides do kode
# Potem pa ti ne dajo izvorne kode.
# ucilnice_install/2022-23/ORS_VGRS_Bulic

- name: Set SiFive Studio install location
  set_fact:
    download_filedest: C:\FreedomStudio-4.18.0.2021-04-1-x86_64-w64-mingw32.zip
- name: Download SiFive
  win_command: wget "https://unilj-my.sharepoint.com/:u:/g/personal/bulic_fri1_uni-lj_si/EdiSnJpoClJLtc3AtcAtEQ4BI76_PeDvL-ZmhxG4OEyvig?e=xBRYcb&download=1" -O "{{ download_filedest }}"
  args:
    creates: "{{ download_filedest }}"

- name: Unzip SiFive Studio
  win_unzip:
    src: "{{ download_filedest }}"
    dest: C:\SiFive\
    creates: C:\SiFive\plugins
    delete_archive: yes

- name: Create desktop shortcut
  win_shortcut:
    description: "SiFive Freedom Studio"
    src: C:\SiFive\FreedomStudio.exe
    dest: '%public%\Desktop\SiFive.lnk'
