- name: Set PyCharm version
  set_fact:
    target_version: "2023.2.1"

- name: Install PyCharm
  win_chocolatey:
    name: pycharm-community
    version: "{{ target_version }}"

# TODO set default project directory to H:\something
