# Uporabniški vmesniki
# Ales.Smrdel@fri.uni-lj.si
# Windows, GNU/Linux, Java JDK, IntelliJ IDEA, javafx, SceneBuilder, X11 development, Wayland development, gtk+ development, glade, python
dependencies:
  - role: jdk
  - role: idea
  - role: javafx
  - role: gui_development
  - role: scenebuilder
