# Osnove umetne inteligence
# Jure.Zabkar@fri.uni-lj.si, Ales.Papic@fri.uni-lj.si, matej.piculin@fri.uni-lj.si, Marko.Zeman@fri.uni-lj.si, bojan.zunkovic@fri.uni-lj.si
# Orange, Weka 3, BayesFusion
dependencies:
  - role: orange
  - role: weka
  - role: bayesfusion
