- name: Install Android Studio
  block:
  - name: Create destination for Android Studio
    file:
      path: /opt/Android_Studio
      state: directory
  - name: Download and unpack Android Studio
    unarchive:
      # src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.3.1.16/android-studio-2021.3.1.16-linux.tar.gz 
      src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.3.1.19/android-studio-2022.3.1.19-linux.tar.gz
      creates: /opt/Android_Studio/android-studio/build.txt
      dest: /opt/Android_Studio
      remote_src: yes
