- name: Install OMNet++
  block:
    - name: Create destination for Omnet++  
      file:
        path: /opt/omnetpp
        state: directory
    - name: Download and unpack Omnet++
      unarchive:
        src: https://github.com/omnetpp/omnetpp/releases/download/omnetpp-6.0.1/omnetpp-6.0.1-linux-x86_64.tgz
        dest: /opt/omnetpp
        remote_src: yes

# TODO install inet system-wide
- name: Install INET Framework
  block:
    - name: Create destination for INET Framework
      file:
        path: /opt/omnetpp-inet
        state: directory
    - name: Download and unpack INET Framework
      unarchive:
        src: https://github.com/inet-framework/inet/releases/download/v4.4.1/inet-4.4.1-src.tgz
        dest: /opt/omnetpp-inet
        remote_src: yes
