# Programiranje 2
# bostjan.slivnik@fri.uni-lj.si
# gedit, vscode, pdf viewer (evince), gcc, g++, make, JDK

- include_tasks: jdk.yml
- include_tasks: gedit.yml
- include_tasks: vscode.yml
- include_tasks: c_development.yml
