# TODO install PowerDesigner
- name: PowerDesigner
  debug:
    msg: "Install PowerDesigner"
- name: Install Wine
  apt:
    name: wine-development
    state: latest
- name: Install Wine binfmt support
  apt:
    name: wine-binfmt
    state: latest
