# Računalniške komunikacije
# Ales.Jaklic@fri.uni-lj.si, Matjaz.Pancur@fri.uni-lj.si, Jure.Tuta@fri.uni-lj.si, Domen.Kosir@fri.uni-lj.si
# GNU/Linux, GNS3, Docker, VS Code, wireshark, Java JDK, Python 3
- include_tasks: docker.yml
- include_tasks: gns3.yml
- include_tasks: vscode.yml
- include_tasks: wireshark.yml
- include_tasks: jdk.yml

