# Vhodno-izhodne naprave
# Robert.Rozman@fri.uni-lj.si
# Windows, Logisim Evolution, RAVINOR, WinIdea 9.12.256 (FRISMS kompatibilna), LTSpice
dependencies:
  - role: logisim
  - role: winidea-frisms
  - role: winidea
  - role: ltspice

