- name: Check javafx install
  win_find:
    paths: "C:\\Program Files\\Java"
    patterns: ['javafx-sdk-*']
    file_type: directory
  register: install

- when: install.matched == 0
  block:
    - name: Download javafx
      win_get_url:
        url: https://download2.gluonhq.com/openjfx/19/openjfx-19_windows-x64_bin-sdk.zip
        dest: C:\
      register: download
    
    - name: Install javafx
      win_unzip:
        src: "{{ download.dest }}"
        dest: "%ProgramFiles%\\Java"
        delete_archive: yes
