- name: Install 7-zip
  win_chocolatey:
    name: 7zip
  register: install

- when: install.changed
  block:
    - name: Create 7-zip filetype
      win_command: cmd.exe /c ftype 7-zip=%ProgramFiles%\7-zip\7zFM.exe
    
    - name: Associate 7-zip with archive filetypes
      win_command: cmd.exe /c assoc .{{ item }}=7-zip
      loop:
        - gz
        - tar
        - targz
        - rar
        - 7z
