- name: Install Chrome
  win_chocolatey:
    name: googlechrome

- name: Disable Chrome updates
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Google\Update
    name: AutoUpdateCheckPeriodMinutes
    type: dword
    data: 0
