- name: Set Eclipse version
  set_fact:
    target_version: "4.25"

- name: Install Eclipse
  win_chocolatey:
    name: eclipse
    version: "{{ target_version }}"

- name: Set up default directories for Eclipse
  win_lineinfile:
    path: "%ProgramFiles%\\Eclipse {{ target_version }}\\eclipse\\eclipse.ini"
    regexp: "osgi.instance.area.default"
    line: "-Dosgi.instance.area.default=H:/Documents/eclipse-workspace"
