# Vzporedni in porazdeljeni sistemi in algoritmi
# Davor.Sluga@fri.uni-lj.si, Rok.Cesnovar@fri.uni-lj.si
# Windows, VS Code, Build Tools for Visual Studio 2022
- include_tasks: vscode.yml
- include_tasks: visual_studio.yml
