- name: Install OpenJDK 18
  apt:
    name: openjdk-18-jdk
    state: latest

- name: Install OpenJDK 19
  apt:
    name: openjdk-19-jdk
    state: latest

- name: Install OpenJDK 11
  apt:
    name: openjdk-11-jdk
    state: latest

- name: Install default JDK
  apt:
    name: default-jdk
    state: latest

- name: Install Java docs
  apt:
    name: default-jdk-doc
    state: latest


- name: Install Oracle Java dependencies
  apt:
    name: 
      - libc6-i386
      - libc6-x32
    state: latest

- name: Install Oracle JDK 20
  apt: 
    deb: "https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.deb"

- name: Install Java docs
  apt: 
    deb: "https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.deb"

