- name: Download mysql ODBC connector (32-bit)
  win_get_url:
    url: https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.33-win32.msi
    dest: C:\mysql-connector-odbc-8.0.33-win32.msi
    http_agent: "Wget/1.21.3"

- name: Install MySQL ODBC connector (32-bit)
  win_package:
    path: c:\mysql-connector-odbc-8.0.33-win32.msi
    product_id: "9F326F09-E926-444B-86E9-1BEA240886A2"

- name: Download mysql ODBC connector (64-bit)
  win_get_url:
    url: https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/mysql-connector-odbc-8.0.33-winx64.msi
    dest: C:\mysql-connector-odbc-8.0.33-winx64.msi
    http_agent: "Wget/1.21.3"

- name: Install MySQL ODBC connector (64-bit)
  win_package:
    path: C:\mysql-connector-odbc-8.0.33-winx64.msi
    product_id: "9AC93A88-9070-47B0-9EFC-DDA915EF22BA"

